### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by winderica** [tumberger/zk-Location#1]
- [x] Check the number of constraints
- [x] Investigate how to use Gnark's logUp
- [x] Lookup table for $2^x$
- [x] Documentation & comments
- [x] Merge `fp` into `feat/math`, or create a `main` branch by combining both?

Feel free to edit the list if you want to add a task or have completed one.

ToDo's added by Jens:
- [X] Migrate F64 to math function implementation by Luca (branch feat/math)
- [x] Generate test files similar to F64 testing for math functions
  - It seems that [Berkeley TestFloat](http://www.jhauser.us/arithmetic/TestFloat-3/doc/TestFloat-general.html) doesn't support generating test cases for complex functions. Are there any other libraries?
- [x] Sanity Check correctness of math function implementation & Clean up current simple migration (NOTE - Testing now checks that ULP <1 - currently this is not the case for all ranges of float values. Better approximation needed, increasing the degree of polynomial in atan or number of round for taylore series in sin is insufficient as it adds too many constraints)
- [x] Check Optimization sqrt - Currently Newton Rhapson, nth Root might be better (shifting/add instead of division) - @winderica will integrate his implementation with supercedes the Newton Rhapson one 
- [ ] Revise Sin implementation with Taylor approximation -> Add F32 support @Luca1011 
- [ ] Replace Sin with Spline approach --> lookup range of value, have low degree polynomial approximate the small range
- [x] Migrate F64 implementation & new Math to zkLocation circuit
- [x] Modularize float implementation to also support F32
     - [x] Add Exponent Bitwidth / Precision in F64 / F32 struct as a constant?
